apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        workstations: ingress
        workstations-ingress-http: allow
        workstations-ingress-https: allow
    spec:
      containers:
      - name: nginx
        image: vmware/nginx-photon:1.11.13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-certificates
          mountPath: /etc/nginx/certs/server.crt
          subPath: tls.crt
        - name: nginx-certificates
          mountPath: /etc/nginx/certs/server.key
          subPath: tls.key
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-certificates
        secret:
          secretName: nginx-certificates
