apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: clair-postgres
spec:
  template:
    metadata:
      name: clair-postgres
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: vmware/postgresql:9.6.4-photon
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: POSTGRESS_ROOT_PASSWORD
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql
        ports:
        - containerPort: 5432
          name: postgres-port
          protocol: TCP
      volumes:
      - name: pgdata
#        persistentVolumeClaim:
#          claimName: postgres-data
        hostPath:
          path: /data/gluster/postgres
