apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
      nodePort: 8889
  clusterIP: 10.254.1.1
  selector:
    app: nginx
  type: NodePort
