apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
      nodePort: $service_port
  clusterIP: $cluster_ip
  selector:
    app: nginx
  type: NodePort
